// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMUP0FEtX3jYpYRwt3Lilzwk9FdQl8SB0',
    appId: '1:1012096468261:web:fe0bddf8b34fcaacda86cc',
    messagingSenderId: '1012096468261',
    projectId: 'todo-mtest-601e5',
    authDomain: 'todo-mtest-601e5.firebaseapp.com',
    storageBucket: 'todo-mtest-601e5.appspot.com',
    measurementId: 'G-TCRWLGKPWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf7JWJLBKWUXG9Hcj02vnY-G-1ggNpJYM',
    appId: '1:1012096468261:android:cea66545b318820dda86cc',
    messagingSenderId: '1012096468261',
    projectId: 'todo-mtest-601e5',
    storageBucket: 'todo-mtest-601e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtT8rrdJG3HrgyjjlNruDXfcNKXTRxDZo',
    appId: '1:1012096468261:ios:56e5a7dee2e36992da86cc',
    messagingSenderId: '1012096468261',
    projectId: 'todo-mtest-601e5',
    storageBucket: 'todo-mtest-601e5.appspot.com',
    iosClientId: '1012096468261-ac7a9a32j83fe9o592ev320nlpl5mgvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoMtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtT8rrdJG3HrgyjjlNruDXfcNKXTRxDZo',
    appId: '1:1012096468261:ios:56e5a7dee2e36992da86cc',
    messagingSenderId: '1012096468261',
    projectId: 'todo-mtest-601e5',
    storageBucket: 'todo-mtest-601e5.appspot.com',
    iosClientId: '1012096468261-ac7a9a32j83fe9o592ev320nlpl5mgvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoMtest',
  );
}
